FROM pytorch/pytorch
COPY . /src
WORKDIR /src


# Install pip dependencies


# Install system dependencies


# 确保 python -c "from infer import Infer, Inputs; Infer().run_inference(Inputs())" 可以正常运行





